name: DEPLOY STAGING

on:
  push:
    branches: [ "development" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Build with tsup
        run: npm run build

  deploy-server-1:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: DEPLOY TO SERVER 1
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            export NVM_DIR="$HOME/.nvm"
            source "$NVM_DIR/nvm.sh"
            nvm use 23
            ls
            echo "==> DEPLOYING ON SERVER"
            cd ~/donation-app
            ls
            pm2 list
            git checkout development
            git pull origin development
            echo "==> CODE PULLED"

            npm install
            echo "==> DEPENDENCIES INSTALLED"

            npm run build
            echo "==> BUILD SUCCESSFUL"

            pm2 stop donation || echo "PM2 process not found"
            pm2 start donation
            echo "==> APP STARTED WITH PM2"